modules:
  tcl:
    ^cuda:
      suffixes:
        +cuda: '{^cuda.name}-{^cuda.version}'
      conflict:
      - '{^cuda.name}'
      environment:
        prepend_path:
          PATH: '{^cuda.prefix}/bin'
          LD_LIBRARY_PATH: '{^cuda.prefix}/lib64'
          CPATH: '{^cuda.prefix}/include'
          C_INCLUDE_PATH: '{^cuda.prefix}/include'
          CPLUS_INCLUDE_PATH: '{^cuda.prefix}/include'
        set:
          CUDA_HOME: '{^cuda.prefix}'
          CUDA_LIB:  '{^cuda.prefix}/lib64'
          CUDA_INC:  '{^cuda.prefix}/include'
          CUDA_INCLUDE: '{^cuda.prefix}/include'


    projections:
      cuda: '{name}/{version}'

