defaults:
  spack_major_version : '0.19'
  spack_minor_version : '1'
  spack_version : '0.19.1'

  origin :
    branches :
      - 'backport/0.19/25727_improve_module_suffixes'
      - 'backport/0.19/35290_fix_test_concretize_together'

