# this is


defaults:
  integration : 'True'
  cache : '../cache'
  install : '../../install'
  clearconfig : 'True'
  origin :
    master : 'integrate/rcm/client'
    branches :
      - 'clean/develop'
      - 'pr/turbovnc'
      - 'pr/fix/flake8_configparser_backport'
      - 'pr/pyinstaller'



  upstream :
    prs :    ["5787" ]



