modules:
  tcl:
    whitelist:
    - py-pexpect
    - py-ptyprocess
    - py-paramiko
    - py-cryptography
    - py-packaging
    - py-cffi
    - py-asn1crypto
    - py-pycrypto
    - py-idna
    - py-ipaddress
    - py-pyasn1
    - tk
    - jdk
    - py-pyinstaller
    - py-dis3
    - py-macholib
    - py-pefile
    - py-altgraph
    - py-future


