packages:
  all:
    providers:
      gl:
        - opengl
        - mesa
  mesa:
    variants:
    - +hwrender
    - ~swrender
  opengl:
    paths:
      opengl@4.5.0: /usr
    buildable: False
  rcm:
    variants:
      - +virtualgl
 
