# this is


defaults:
  integration : 'True'
  clearconfig : 'True'
  origin :
    branches :
      - 'pr/turbovnc'
      - 'pr/fix/flake8_configparser_backport'
      - 'pull/rebased/2771'
      - 'pr/fix/perl-dependent-modules'


  upstream :
    prs :
      - '5787'





