# this is


defaults:
  integration_name: 'rcm'
  origin :
    url : 'https://github.com/RemoteConnectionManager/spack.git'
    master: 'clean/develop'
    branches :
      - 'packages/turbovnc'
      - 'packages/libjpeg-turbo'
#      - 'pr/pyinstaller'
#fixed with merged 7493#      - 'pr/fix/glib_dtrace_pythonhome'
#      - 'packages/qt5-dbus'
#merged      - 'pr/fix/bdftopcf'
#merged      - 'pr/fix/xinput'






