# this is


defaults:
  origin :
    url : 'https://github.com/RemoteConnectionManager/spack.git'
  integration : 'True'
  clearconfig : 'True'
  origin :
    master : 'integrate/rcm'
    branches :
      - 'pr/turbovnc'
      - 'pr/pyinstaller'
#fixed with merged 7493#      - 'pr/fix/glib_dtrace_pythonhome'
      - 'packages/qt5-dbus'
#merged      - 'pr/fix/bdftopcf'
#merged      - 'pr/fix/xinput'






