# this is


defaults:
  integration : 'True'
  clearconfig : 'True'
  origin :
    master : 'integrate/rcm'
    branches :
      - 'pr/turbovnc'
      - 'pr/pyinstaller'
#fixed with merged 7493#      - 'pr/fix/glib_dtrace_pythonhome'
      - 'pr/fix-qt5-opengl'
#merged      - 'pr/fix/bdftopcf'
#merged      - 'pr/fix/xinput'






