defaults:
  upstream :
    prs :
      - '24156' #modules: allow user to remove arch dir
      - '24367' #modules: configurable module defaults
      - '25727' #Modules: Allow spec formatting in suffixes
        #already merged      - '25636' #gui support for vtk 9
      - '23489' #GROMACS build several flafors
        #modified and integrated into packages/0.16/pr_fix_25976_mesa_demos# - '25976' #fix opengl version and add mesa-demos



