defaults:
  origin:
    branches:
      - 'packages/0.18/fix_plumed_gromacs'
      - 'packages/0.16/base/gsl_update'
#      - 'packages/0.16/base/fix_plumed_cblas'
      - 'packages/0.17/fix_gdal_json-c#23943'
#null change branch      - 'packages/0.18/fix_gdal_json-c#30809'
      - 'packages/0.17/fix_mpfr'
      - 'packages/0.18/fix_eccodes_intel_openmp'
