spack:
  packages:
    cuda:
      externals:: []

  definitions:
  - all:
    - gcc@10.2.0 +nvptx ~bootstrap
    - cuda
  - system_compiler:
    - '%${SYS_GCC}'
  specs:
  - matrix:
    - - $all
    - - $system_compiler
  view: false
  concretization: together
