defaults:
  config_setup:
    spack_commands:
      # install intel-oneapi-compilers
      - 'spack install intel-oneapi-compilers%gcc'
      # map newly installed intel-oneapi-compilers in the standard intel suggested way: https://software.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-linux/top/installation/install-using-package-managers/spack.html
      - 'export DEPLOY_INTEL_PREFIX=$(spack location -i intel-oneapi-compilers); spack compiler add --scope site $DEPLOY_INTEL_PREFIX/compiler/latest/linux/bin/intel64; spack compiler add --scope site $DEPLOY_INTEL_PREFIX/compiler/latest/linux/bin'
      # insert a custom compiler mapping mixing old intel for fortran and the new intel-oneapi for the c-cpp stuff
      - 'export DEPLOY_INTEL_PREFIX=$(spack location -i intel-oneapi-compilers); export DEPLOY_INTEL_VERSION=$(spack find --format {version} intel-oneapi-compilers | cut -d@ -f2); export DEPLOY_OS=$(spack arch -o); envsubst <{{DEPLOY_ROOTPATH}}/config/intel/oneapi/oneapi_xxx_compiler.yaml  > /tmp/add_compiler.yaml'
      - 'spack config  --scope site add -f /tmp/add_compiler.yaml'
      #  with system gcc ( now is the only one gcc compiler) nstall intel-oneapi-<component> : mpi mkl and tbb as a dep 
      - 'spack install intel-oneapi-mpi%gcc'
      - 'spack install intel-oneapi-mkl%gcc'
      # define installed intel-oneapi-<component>  as external
      - '/bin/bash {{DEPLOY_ROOTPATH}}/scripts/add_external.sh {{DEPLOY_ROOTPATH}}/config/templates/external_packages.yaml intel-oneapi-mpi%gcc intel-oneapi-mkl%gcc intel-oneapi-tbb%gcc '
