modules:
  default:
    tcl:
      include:
      - intel-oneapi-compilers
      - intel-oneapi-mkl
      - intel-oneapi-mpi
      - intel-oneapi-vtune

      intel-oneapi-mpi:
        environment:
          set:
            MPICC: mpiicc
            MPICXX: mpiicpc
            MPIF90: mpiifort
            MPIF77: mpiifort
            MPIFC: mpiifort

 
      intel-oneapi-mpi%oneapi:
        environment:
          set:
            MPICC: mpiicc -cc=icx
            MPICXX: mpiicpc -cxx=icpx
