compilers:
- compiler:
    spec: oneapi@2021.3.0-ifort
    paths:
      cc: ${DEPLOY_INTEL_PREFIX}/compiler/${DEPLOY_INTEL_VERSION}/linux/bin/icx
      cxx: ${DEPLOY_INTEL_PREFIX}/compiler/${DEPLOY_INTEL_VERSION}/linux/bin/icpx
      f77: ${DEPLOY_INTEL_PREFIX}/compiler/${DEPLOY_INTEL_VERSION}/linux/bin/intel64/ifort
      fc: ${DEPLOY_INTEL_PREFIX}/compiler/${DEPLOY_INTEL_VERSION}/linux/bin/intel64/ifort
    flags: {}
    operating_system: ${DEPLOY_OS}
    target: x86_64
    modules: []
    environment:
      set:
        INTEL_HOME: ${DEPLOY_INTEL_PREFIX}
#        LD_LIBRARY_PATH: /cineca/prod/opt/compilers/intel/oneapi-2021/binary/compiler/latest/linux/compiler/lib/intel64
#    extra_rpaths:
#    - /cineca/prod/opt/compilers/intel/oneapi-2021/binary/compiler/2021.2.0/linux/compiler/lib/intel64_lin
#    - /cineca/prod/opt/compilers/intel/oneapi-2021/binary/itac/2021.2.0/bin
#    - /cineca/prod/opt/compilers/intel/oneapi-2021/binary/inspector/2021.2.0/lib64

