spack:
  definitions:
  - all:
    - intel-oneapi-compilers
    - intel-oneapi-mpi
    - intel-oneapi-mkl
    - intel-oneapi-vtune
  - system_compiler:
    - '%${SYS_GCC}'
  specs:
  - matrix:
    - - $all
    - - $system_compiler
  view: false
  concretization: together
