packages:
  all:
    providers:
      gl:
        - opengl
        - mesa
      glx:
        - opengl
        - mesa+glx
      glu:
        - openglu
        - mesa-glu
  rcm:
    variants:
      - +virtualgl
 
