defaults:
  spack_major_version : '0.18'
  spack_version : '0.18.1'
  generated_subdir : 'generated_envs'
  upstream :
    master : "v0.18.1"
    prs :
      #already merged - '24156' #modules: allow user to remove arch dir
      #already merged - '24367' #modules: configurable module defaults
      - '25727' #Modules: Allow spec formatting in suffixes
        #already merged      - '25636' #gui support for vtk 9

  origin :
    integration_branch: '{{ defaults.integration_type }}{{DEPLOY_WORKNAME}}_{{ defaults.spack_version }}'
    url : 'https://github.com/RemoteConnectionManager/spack.git'
    master: 'clean/{{ defaults.spack_version }}'
#    branches:
#      - 'packages/0.17/fix_mumps_mk'
#      - 'packages/0.17/fix_petsc_fftw_intel'

  upstream_rebase: 'True'
  upstream_update: 'True'

  runconfig: 'True'
  integration: 'True'
logging_configs:
  loggers:
    cascade_yaml_config:
      level: WARNING



