config:
  build_stage:
  - $tempdir

  source_cache: "{{DEPLOY_SPACK_CACHE}}"
  install_tree: "{{DEPLOY_SPACK_INSTALL}}"
  module_roots:
    tcl: "{{DEPLOY_SPACK_MODULES}}"

  install_tree:
    root: "{{DEPLOY_SPACK_INSTALL}}"

  misc_cache: "{{DEPLOY_SPACK_INSTALL}}/__misc_cache"


