# -------------------------------------------------------------------------
# This is the default spack module files generation configuration.
#
# Changes to this file will affect all users of this spack install,
# although users can override these settings in their ~/.spack/modules.yaml.
# -------------------------------------------------------------------------
modules:
  enable:
    - tcl
  tcl:
    naming_scheme:  '${PACKAGE}/${VERSION}-${COMPILERNAME}-${COMPILERVER}'
    whitelist: ['turbovnc', 'nasm', 'cmake']
    blacklist: ['%gcc@4.8.5']
    hash_length: 2
    all:
      environment:
        set:
          '${PACKAGE}_HOME': '${PREFIX}'
      conflict: ['${PACKAGE}']
#    ^python:
    rcm:
      autoload: 'direct'

