modules:
  tcl:
    whitelist:
    - paraview
    - openmpi
    - py-matplotlib
    - py-cycler
    - py-six
    - py-dateutil
    - py-functools32
    - py-numpy
    - py-pillow
    - py-pyparsing
    - py-pytz
    - py-setuptools
    - py-appdirs
    - py-packaging
    - py-subprocess32
