defaults:
  origin:
    branches:
#      - 'packages/0.16/base/intel_onapi_fixes'
#      - 'packages/0.17/fix_boost_intel_on_compute_nodes'
      - 'packages/0.17/fix_nwchem'
      - 'packages/0.17/fix_nco_intel_issue_243'
