# this is


defaults:
  integration : 'True'
  clearconfig : 'True'
  origin :
    master : 'integrate/insitu'
    branches :
      - 'packages/qt5-dbus'
      - 'packages/qt5-virtualgl'
# merged      - 'packages/of-paraview-catalyst'
#  upstream :
#    prs :
#      - '8070'







