# this is


defaults:
  integration : 'True'
  clearconfig : 'True'
  origin :
    branches :
      - 'pr/insitu-paraview-catalyst'
      - 'pr/fix-qt5-opengl'
#merged      - 'pr/fix-mesa-urls'






