packages:
  paraview:
    variants:
     -  +opengl2
     -  +mpi
     -  +python
     -  +qt
     -  +hdf5
     -  +examples
  catalyst:
    variants:
    - +essentials
    - +extras
    - +python
    - +rendering


