modules:
  tcl:
    whitelist:
    - xauth
    - xkbcomp
    - xedit
    - emacs
    - xlsfonts
    - xdpyinfo
    - xfontsel
    - fluxbox
    - lxde-lxterminal
    - lxde-libfm
    - lxde-menu-cache
