modules:
  tcl:
    whitelist:
    - xauth
    - xhost
    - xkbcomp
    - xedit
    - emacs
    - image-magick
    - xlsfonts
    - xdpyinfo
    - xfontsel
    - fluxbox
    - lxde-lxterminal
    - lxde-libfm
    - lxde-menu-cache
    - pcmanfm
    - tint2
    - openbox
    - leafpad
    - gpicview
    - lxde-icon-theme
    - py-six
