modules:
  tcl:
    whitelist:
    - xauth
    - xhost
    - xkbcomp
    - xedit
    - emacs
    - image-magick
    - xlsfonts
    - xdpyinfo
    - xfontsel
    - fluxbox
    - lxde-lxterminal
    - lxde-libfm
    - lxde-menu-cache
    - lxde-pcmanfm
    - lxde-tint2
    - lxde-openbox
    - lxde-leafpad
    - lxde-gpicview
    - lxde-icon-theme
    - py-six
