packages:
  xkeyboard-config:
    variants: +xorg
  font-util:
    variants:
    - fonts=font-adobe-75dpi
  turbovnc:
    variants: 
    - +x11deps
    - +server
  qt:
    variants: 
    - +examples
    - +opengl
    - +dbus
  emacs:
    variants: 
    - +X 
    - toolkit=gtk
  rcm:
    variants:
      - +server 
      - configdir=@{RCM_DEPLOY_HOSTPATH}/rcm

