spack:
  definitions:
  - selected_openssl:
    - ${openssl_SPEC}
  - tools:
    - cmake
    - git
    - perl
    - autoconf
    - automake
    - m4
    - patchelf

  - all:
    - $selected_openssl
    - $tools
  - system_compiler:
    - '%${SYS_GCC}'
  specs:
  - matrix:
    - - $all
    - - $system_compiler
  view: false
  concretization: together
