spack:
  definitions:
  - selected_openssl:
    - ${openssl_SPEC}

  - othertools:
    - git
    - perl
    - patchelf

  - utils:
    - libtool
    - bison
    - diffutils
    - pkgconf

  - assemblers:
    - nasm
    - yasm

  - autotools:
    - autoconf
    - autoconf-archive
    - automake
    - m4
    - texinfo
    - gmake

  - cmaketools:
    - cmake
    - ninja

  - all:
    - $selected_openssl
    - $autotools
    - $cmaketools
    - $othertools
    - $utils
    - $assemblers

  - system_compiler:
    - '%${SYS_GCC}'
  specs:
  - matrix:
    - - $all
    - - $system_compiler
  view: false
  concretization: together
