defaults:
#  generate_env:
#    config_commands:
#      - 'spack external find --scope site openssl'

  origin:
    branches:
      - 'packages/0.19/fix_rust_system_openssl'
      - 'packages/0.19/undeprecate_system_openssl'

