defaults:
  config_setup:
    spack_commands:
      # install latest available nvhpc including it's mpi
      - 'export SYS_COMPILER_SPEC=$(spack-python {{DEPLOY_ROOTPATH}}/scripts/select_spec.py); spack spec -I nvhpc%${SYS_COMPILER_SPEC} +mpi'
      - 'export SYS_COMPILER_SPEC=$(spack-python {{DEPLOY_ROOTPATH}}/scripts/select_spec.py); spack install nvhpc%${SYS_COMPILER_SPEC} +mpi'
      # map new nvhpc compiler
      - 'export dummy; spack load $(spack-python {{DEPLOY_ROOTPATH}}/scripts/select_spec.py --tplfile spec_tpl.yaml --add nvhpc); spack compiler find --scope site; spack unload nvhpc'


